appName: servicename
appImage: 
appVersion: 1.0.0
appReplicas: 1
containerPort: 8080
containerEnvVars: 
- name: ENV_VAR_ONE
  value: "valueone"
- name: ENV_VAR_TWO
  value: "valuetwo"

serviceType: ClusterIP
servicePort: 8080